<a href="https://colab.research.google.com/github/Pragati-cloud/Data-Science-Machine-Learning-Deep-Learning-NLP-By-KrishNaik/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
df = pd.read_csv("Travel.csv")
df.head()

   CustomerID  ProdTaken  ...  Designation MonthlyIncome
0      200000          1  ...      Manager       20993.0
1      200001          0  ...      Manager       20130.0
2      200002          1  ...    Executive       17090.0
3      200003          0  ...    Executive       17909.0
4      200004          0  ...    Executive       18468.0

[5 rows x 20 columns]

In [5]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [6]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [7]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [8]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [9]:
df['Gender']= df['Gender'].replace("Fe Male","Female")
df['MaritalStatus'] = df['MaritalStatus'].replace("Single","Unmaaried")

In [10]:
df.head()

   CustomerID  ProdTaken  ...  Designation MonthlyIncome
0      200000          1  ...      Manager       20993.0
1      200001          0  ...      Manager       20130.0
2      200002          1  ...    Executive       17090.0
3      200003          0  ...    Executive       17909.0
4      200004          0  ...    Executive       18468.0

[5 rows x 20 columns]

In [11]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [12]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Unmaaried     916
Unmarried     682
Name: count, dtype: int64

In [13]:
df['MaritalStatus'] = df['MaritalStatus'].replace("Unmaaried","Unmarried")
df['MaritalStatus'] = df['MaritalStatus'].replace("Unmaried","Unmarried")

In [14]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [15]:
df['Gender']= df['Gender'].map({'Male':1,'Female':0})
df['MaritalStatus']= df['MaritalStatus'].map({'Married':1,'Unmarried':2, 'Divorced':3})
df['TypeofContact']= df['TypeofContact'].map({'Self Enquiry':1,'Company Invited':2})

In [16]:
df.head()

   CustomerID  ProdTaken  ...  Designation  MonthlyIncome
0      200000          1  ...      Manager        20993.0
1      200001          0  ...      Manager        20130.0
2      200002          1  ...    Executive        17090.0
3      200003          0  ...    Executive        17909.0
4      200004          0  ...    Executive        18468.0

[5 rows x 20 columns]

In [17]:
df['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [18]:
## checking missing values

feature_with_na = [features for features in df.columns if df[features].isnull().sum()>1]

for feature in feature_with_na:
    print(feature, np.round(df[feature].isnull().mean()*100, 4),  ' % missing values')

Age 4.6236  % missing values
TypeofContact 0.5115  % missing values
DurationOfPitch 5.135  % missing values
NumberOfFollowups 0.9206  % missing values
PreferredPropertyStar 0.5319  % missing values
NumberOfTrips 2.8642  % missing values
NumberOfChildrenVisiting 1.3502  % missing values
MonthlyIncome 4.7668  % missing values

In [19]:
df[feature_with_na].select_dtypes(exclude='object').describe()

               Age  TypeofContact  ...  NumberOfChildrenVisiting  MonthlyIncome
count  4662.000000    4863.000000  ...               4822.000000    4655.000000
mean     37.622265       1.291795  ...                  1.187267   23619.853491
std       9.316387       0.454635  ...                  0.857861    5380.698361
min      18.000000       1.000000  ...                  0.000000    1000.000000
25%      31.000000       1.000000  ...                  1.000000   20346.000000
50%      36.000000       1.000000  ...                  1.000000   22347.000000
75%      44.000000       2.000000  ...                  2.000000   25571.000000
max      61.000000       2.000000  ...                  3.000000   98678.000000

[8 rows x 8 columns]

In [20]:
df.Age.fillna(df.Age.median(),inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)

In [21]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [22]:
df.drop('CustomerID',inplace=True,axis=1)

In [23]:
##Feature Engineering

df['Total_Visits']=df['NumberOfChildrenVisiting']+df['NumberOfPersonVisiting']
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],axis=1, inplace=True)
df.head()

   ProdTaken   Age  TypeofContact  ...  Designation  MonthlyIncome Total_Visits
0          1  41.0            1.0  ...      Manager        20993.0          3.0
1          0  49.0            2.0  ...      Manager        20130.0          5.0
2          1  37.0            1.0  ...    Executive        17090.0          3.0
3          0  33.0            2.0  ...    Executive        17909.0          3.0
4          0  36.0            1.0  ...    Executive        18468.0          2.0

[5 rows x 18 columns]

In [24]:
#get numerical features

num_features= [features for features in df.columns if df[feature].dtype !='O']
print('Number of numerical variables:',len(num_features))

Number of numerical variables: 18

In [25]:
## Categorical Features

cat_features= [features for features in df.columns if df[feature].dtype =='O']
print('Number of categorical variables:',len(cat_features))

Number of categorical variables: 0

In [26]:
##discrete_features
discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
print('Number of discrete variables:',len(discrete_features))

Number of discrete variables: 15

In [27]:
##continues_features
continue_features = [feature for feature in num_features if feature is not discrete_features]
print('Number of continous variables:',len(continue_features))

Number of continous variables: 18

In [28]:
df.head()

   ProdTaken   Age  TypeofContact  ...  Designation  MonthlyIncome Total_Visits
0          1  41.0            1.0  ...      Manager        20993.0          3.0
1          0  49.0            2.0  ...      Manager        20130.0          5.0
2          1  37.0            1.0  ...    Executive        17090.0          3.0
3          0  33.0            2.0  ...    Executive        17909.0          3.0
4          0  36.0            1.0  ...    Executive        18468.0          2.0

[5 rows x 18 columns]

In [29]:
from sklearn.model_selection import train_test_split
X= df.drop(['ProdTaken'],axis=1)
y = df['ProdTaken']

In [30]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [31]:
X.head()

    Age  TypeofContact  CityTier  ...  Designation MonthlyIncome  Total_Visits
0  41.0            1.0         3  ...      Manager       20993.0           3.0
1  49.0            2.0         1  ...      Manager       20130.0           5.0
2  37.0            1.0         1  ...    Executive       17090.0           3.0
3  33.0            2.0         1  ...    Executive       17909.0           3.0
4  36.0            1.0         1  ...    Executive       18468.0           2.0

[5 rows x 17 columns]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
X_train.shape, X_test.shape

((3910, 17), (978, 17))

In [34]:
## Create column transformer with 3 types of transformers

cat_features = X.select_dtypes(include='object').columns
num_features = X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),
    ]
)

In [36]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['Occupation', 'ProductPitched', 'Designation'], dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'TypeofContact', 'CityTier', 'DurationOfPitch', 'Gender',
       'NumberOfFollowups', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'MonthlyIncome', 'Total_Visits'],
      dtype='object'))])

In [35]:
X_train= preprocessor.fit_transform(X_train)
X_test= preprocessor.transform(X_test)

In [38]:
##  - model training

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score

In [40]:
models= {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    #make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    #train set performance
    model_train_accuracy = accuracy_score(y_train, y_train_pred) #train accuracy
    model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')
    model_train_precision = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    moddel_train_roc_auc = roc_auc_score(y_train, y_train_pred)

    #test set performance

    model_test_accuracy = accuracy_score(y_test, y_test_pred) #test accuracy
    model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')
    model_test_precision = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    moddel_test_roc_auc = roc_auc_score(y_test, y_test_pred)

    print(model_train_accuracy)
    print(model_train_f1)
    print(model_train_precision)
    print(model_train_recall)
    print(moddel_test_roc_auc)

1.0
1.0
1.0
1.0
0.8109595055782115
0.8391304347826087
0.809465767117092
0.6736111111111112
0.2661179698216735
0.6227838501300585
1.0
1.0
1.0
1.0
0.8495679131435567